server:
  port: 8500
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**,/address/**,/cart/**,/coupon/**,
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/sso/**
        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/order/**,/item/**
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
feign:
  circuitbreaker:
    enabled: true



