server:
  port: 8086
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/summer
    username: root
    password: 575888hmq
  redis:
    cluster:
      nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:6001,127.0.0.1:6002,127.0.0.1:6003
feign:
  circuitbreaker:
    enabled: true
security:
  oauth2:
    client:
        #基操
       client-id: web
       client-secret: 654321
    resource:
        #因为资源服务器得验证你的Token是否有访问此资源的权限以及用户信息，所以只需要一个验证地址
       token-info-uri: http://localhost:8084/sso/oauth/check_token
       jwt:
        key-value: lbwnb #注意这里要跟验证服务器的密钥一致，这样算出来的签名才会一致

