server:
  port: 8082
spring:
  application:
    name: store-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssmtest
    username: root
    password: 575888hmq
feign:
  circuitbreaker:
    enabled: true
eureka:
  client:
    # 跟上面一样，需要指向Eureka服务端地址，这样才能进行注册
    service-url:
      defaultZone: http://localhost:8888/eureka
