server:
  port: 8083
spring:
  application:
    name: rabbitmq-service
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
    virtual-host: /test
    port: 15672
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssmtest
    username: root
    password: 575888hmq
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
feign:
  circuitbreaker:
    enabled: true



